---
- src: arknoll.selenium
- src: geerlingguy.adminer
- src: geerlingguy.apache
- src: geerlingguy.composer
- src: geerlingguy.daemonize
- src: geerlingguy.drupal-console
- src: geerlingguy.drush
- src: geerlingguy.firewall
- src: geerlingguy.git
- src: geerlingguy.java
- src: geerlingguy.mailhog
- src: geerlingguy.memcached
- src: geerlingguy.mysql
- src: geerlingguy.nginx
- src: geerlingguy.nodejs
- src: geerlingguy.php
- src: geerlingguy.php-memcached
- src: geerlingguy.php-mysql
- src: geerlingguy.php-pecl
- src: geerlingguy.php-xdebug
- src: geerlingguy.php-xhprof
- src: geerlingguy.pimpmylog
- src: geerlingguy.postfix
- src: geerlingguy.repo-remi
- src: geerlingguy.ruby
- src: geerlingguy.security
- src: geerlingguy.solr
- src: geerlingguy.varnish
