services: docker
language: node_js
node_js:
  - v5
  - v4
env:
  global:
      DRUSH_BIN: drush
      MDSK_DIR: /var/www/mdsktest
  matrix:
    # Defaults - Ubuntu 16.04.
    - type: defaults
      distro: ubuntu1604
      init: /sbin/init
      run_opts: "--privileged"
before_install:
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'
before_script:
  - npm install -g gulp yo
  - apt-cache search php
  - sudo apt-get install php5.6 php5.6-xml
script:
  - 'npm test'
  - 'tmpfile=$(mktemp)'
  - 'ln -s ${PWD} ~/.nvm/versions/node/`node -v`/lib/node_modules'
  - 'ls ~/.nvm/versions/node/`node -v`/lib/node_modules/'
  - 'mkdir $HOME/mdsktest && cd $HOME/mdsktest'
  - 'yo mdsk --humanName="mdsktest" --machineName="mdsktest" --drupalVersion=7 --skip-install'
  - 'composer install'
  - 'npm install'
  - './scripts/local_settings.sh'
  - './node_modules/.bin/aquifer build'
  - 'docker run --detach --volume="${PWD}":"${MDSK_DIR}":rw ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${tmpfile}"'
  - 'container_id=$(cat ${tmpfile})'
  - 'docker exec ${container_id} ansible-galaxy install -r "$MDSK_DIR"/provisioning/requirements.yml --force'
  - 'docker exec ${container_id} ansible-playbook "$MDSK_DIR"/provisioning/playbook.yml'
before_deploy:
  - npm install -g gulp
  - npm install gulp
deploy:
  provider: npm
  email: kporras07@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
