language: node_js
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
before_script:
  - npm install -g gulp
script: npm test
deploy:
  provider: npm
  email: kporras07@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
