language: node_js
node_js:
  - v5
  - v4
before_script:
  - npm install -g gulp
script: npm test
before_deploy:
  - npm install -g gulp
deploy:
  provider: npm
  email: kporras07@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
