---
- name: Get software for Python-based control.
  yum: "name={{ item }} state=installed"
  with_items:
    - "curl"
    - "python-pycurl"
    - "@development"

- name: Enable remi repo for MySQL.
  set_fact: mysql_enablerepo="remi"

- name: Enable remi repo for PHP 5.5.
  set_fact: php_enablerepo="remi,remi-php55"
  when: php_version == "5.5"

- name: Enable remi repo for PHP 5.6.
  set_fact: php_enablerepo="remi,remi-php56"
  when: php_version == "5.6"

- name: Enable remi repo for PHP 7.0.
  set_fact: php_enablerepo="remi,remi-test"
  when: php_version == "7.0"
