---
- name: Ensure MySQL AppArmor profile is disabled (for slow query log).
  file:
    path: /etc/apparmor.d/disable/usr.sbin.mysqld
    src: /etc/apparmor.d/usr.sbin.mysqld
    state: link
  register: mysql_apparmor
  when: mysql_slow_query_log_enabled

- name: Restart AppArmor if necessary.
  service: name=apparmor state=restarted
  when: mysql_apparmor.changed
