---
- name: Ensure drupal_core_path directory exists.
  file:
    path: "{{ drupal_core_path }}"
    state: directory
    mode: 0775
  become: no
  when: drupal_site.stat.exists == false

- name: Generate Drupal site with drush makefile.
  command: >
    {{ drush_path }} make -y {{ drush_makefile_path }} --no-gitinfofile
    chdir={{ drupal_core_path }}
  when: drupal_site.stat.exists == false
  become: no
