---
- src: arknoll.selenium
  version: 1.2.0
- src: franklinkim.newrelic
  version: 1.2.0
- src: geerlingguy.adminer
  version: 1.1.0
- src: geerlingguy.apache
  version: 1.7.2
- src: geerlingguy.apache-php-fpm
  version: 1.0.2
- src: geerlingguy.blackfire
  version: 1.0.0
- src: geerlingguy.composer
  version: 1.4.0
- src: geerlingguy.daemonize
  version: 1.1.0
- src: geerlingguy.drupal-console
  version: 1.0.7
- src: geerlingguy.drush
  version: 1.1.2
- src: geerlingguy.firewall
  version: 1.0.9
- src: geerlingguy.git
  version: 1.1.1
- src: geerlingguy.java
  version: 1.4.0
- src: geerlingguy.mailhog
  version: 1.1.0
- src: geerlingguy.memcached
  version: 1.0.4
- src: geerlingguy.mysql
  version: 2.2.1
- src: geerlingguy.nginx
  version: 1.9.2
- src: geerlingguy.nodejs
  version: 3.1.0
- src: geerlingguy.php
  version: 3.1.0
- src: geerlingguy.php-memcached
  version: 2.0.0
- src: geerlingguy.php-mysql
  version: 2.0.0
- src: geerlingguy.php-pecl
  version: 1.2.1
- src: geerlingguy.php-redis
  version: 3.0.0
- src: geerlingguy.php-xdebug
  version: 2.1.0
- src: geerlingguy.php-xhprof
  version: 2.1.2
- src: geerlingguy.pimpmylog
  version: 1.0.2
- src: geerlingguy.postfix
  version: 1.1.0
- src: geerlingguy.redis
  version: 1.2.0
- src: geerlingguy.repo-remi
  version: 1.2.0
- src: geerlingguy.ruby
  version: 2.3.1
- src: geerlingguy.security
  version: 1.2.0
- src: geerlingguy.solr
  version: 3.1.0
- src: geerlingguy.varnish
  version: 1.6.1
